[package]
name = "protocol"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bincode = { version = "2.0.1", features = ["serde"] }
fedimint-lnv2-common = "0.7.1"
iroh = { version = "0.34.1", features = ["discovery-local-network"] }
iroh-blobs = "0.34.1"
iroh-docs = { version = "0.34.0", features = ["rpc"] }
iroh-gossip = "0.34.1"
quic-rpc = "0.19.0"
serde_json = "1.0.140"

[dev-dependencies]
fedimint-core = "0.7.1"
fedimint-tpe = "0.7.1"
tempfile = "3.19.1"
tokio = "1.45.0"
