[workspace]
members = [
    "fedimintd",
    "fedimint-cli",
    "machine",
    "manager",
    "shared",
    "tests"
]
resolver = "3"

[workspace.lints.clippy]
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
missing_const_for_fn = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
option_if_let_else = "allow"

[workspace.dependencies]
anyhow = "1.0.98"
bincode = { version = "2.0.1", features = ["serde"] }
devimint = "0.7.2"
fedimintd = "0.7.2"
fedimint-core = "0.7.2"
fedimint-lnv2-common = "0.7.2"
fedimint-tpe = "0.7.2"
iroh = { version = "0.34.1", features = ["discovery-local-network"] }
iroh-blobs = "0.34.1"
iroh-docs = { version = "0.34.0", features = ["rpc"] }
iroh-gossip = "0.34.1"
machine = { path = "./machine" }
manager = { path = "./manager" }
n0-future = "0.1.3"
quic-rpc = "0.19.0"
rand = "0.8.5"
serde = "1.0.219"
serde_json = "1.0.140"
sha2 = "0.10"
shared = { path = "./shared" }
tempfile = "3.20.0"
tokio = { version = "1.45.0", features = ["macros", "rt"] }
uuid = { version = "1.16.0", features = ["v4"] }

[profile.dev]
split-debuginfo = "packed"

# In dev mode, optimize perf-critical crates (usually just crypto crates).
[profile.dev.package]
secp256k1 = { opt-level = 3 }
secp256k1-sys = { opt-level = 3 }
bitcoin_hashes = { opt-level = 3 }
ff = { opt-level = 3 }
group = { opt-level = 3 }
tikv-jemalloc-sys = { opt-level = 3 }
pairing = { opt-level = 3 }
rand_core = { opt-level = 3 }
byteorder = { opt-level = 3 }
zeroize = { opt-level = 3 }
bls12_381 = { opt-level = 3 }
subtle = { opt-level = 3 }
ring = { opt-level = 3 }

[profile.ci]
inherits = "dev"
debug = "line-tables-only"
incremental = false

[profile.release]
debug = "line-tables-only"
