[package]
name = "manager"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
fedimint-core = { workspace = true }
iroh-docs = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
shared = { workspace = true }